name: Build and Release

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      
    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Run tests
      run: cargo test --verbose
      
    - name: Run clippy
      run: cargo clippy -- -D warnings

  build:
    needs: test
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Tauri CLI
      run: cargo install tauri-cli
      
    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Build release
      run: cargo tauri build
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: isBattery-windows
        path: |
          target/release/bundle/**/*.msi
          target/release/bundle/**/*.exe
          target/release/isbattery.exe

  release:
    needs: build
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Tauri CLI
      run: cargo install tauri-cli
      
    - name: Build release
      run: cargo tauri build
      
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        body: |
          ## 更新内容
          
          - 实时电源状态监控
          - 功率负载监控和显示
          - 智能提醒系统
          - 系统托盘集成
          - 开机自启动支持
          
          ## 安装说明
          
          1. 下载对应的安装包
          2. 运行安装程序
          3. 启动程序后会出现在系统托盘
          
          ## 系统要求
          
          - Windows 10/11
          - .NET Framework 4.7.2 或更高版本
      
    - name: Upload Release Asset (MSI)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: target/release/bundle/msi/isBattery_0.1.0_x64_en-US.msi
        asset_name: isBattery-0.1.0-windows-x64.msi
        asset_content_type: application/x-msi
        
    - name: Upload Release Asset (EXE)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: target/release/isbattery.exe
        asset_name: isBattery-0.1.0-windows-x64.exe
        asset_content_type: application/octet-stream